// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFR2jx2QzZNbNENmHw4iCGqRDTrFxWzCo',
    appId: '1:104780306420:web:29da1b479bbb9fb00f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    authDomain: 'sbsr-g.firebaseapp.com',
    databaseURL: 'https://sbsr-g-default-rtdb.firebaseio.com',
    storageBucket: 'sbsr-g.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZkBZiZ-9jzBu15Gn9dIfxptsL19gUEfk',
    appId: '1:104780306420:android:c9ba1081d4e2a5630f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    databaseURL: 'https://sbsr-g-default-rtdb.firebaseio.com',
    storageBucket: 'sbsr-g.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_gqgApqKp81_aSUhKCZdwsaZZLIqrkY0',
    appId: '1:104780306420:ios:f32b3b50354ae2880f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    databaseURL: 'https://sbsr-g-default-rtdb.firebaseio.com',
    storageBucket: 'sbsr-g.appspot.com',
    androidClientId: '104780306420-shduuld8k4328esp0p9v3ajfou3bvhic.apps.googleusercontent.com',
    iosClientId: '104780306420-l4bap26tme79rm2c4g8tsrfo1s4cerl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbsrAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_gqgApqKp81_aSUhKCZdwsaZZLIqrkY0',
    appId: '1:104780306420:ios:f32b3b50354ae2880f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    databaseURL: 'https://sbsr-g-default-rtdb.firebaseio.com',
    storageBucket: 'sbsr-g.appspot.com',
    androidClientId: '104780306420-shduuld8k4328esp0p9v3ajfou3bvhic.apps.googleusercontent.com',
    iosClientId: '104780306420-l4bap26tme79rm2c4g8tsrfo1s4cerl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbsrAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFR2jx2QzZNbNENmHw4iCGqRDTrFxWzCo',
    appId: '1:104780306420:web:29da1b479bbb9fb00f8ba1',
    messagingSenderId: '104780306420',
    projectId: 'sbsr-g',
    authDomain: 'sbsr-g.firebaseapp.com',
    databaseURL: 'https://sbsr-g-default-rtdb.firebaseio.com',
    storageBucket: 'sbsr-g.appspot.com',
  );
}
